
[build]
  functions = "functions"
  publish = "static" # ここは通常使われませんが、念のため設定

[functions]
  included_files = ["templates/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200