
[build]
  functions = "functions"
  publish = "templates"

[functions]
  included_files = ["templates/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200